application: weightmange
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico
  mime_type: image/x-icon
- url: /js
  static_dir: js
- url: /.*
  script: proxy.py
